#!/bin/sh
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright (c) 2010 Oracle and/or its affiliates. All rights reserved.
#
# Use is subject to License Terms
#

"/home/ron/glassfish3/glassfish/bin/asadmin" start-domain domain1
